name: wireguard-hs
version: 0.1.0
synopsis: API for Linux Kernel Wireguard device management
author: Travis Athougies
maintainer: travis@athougies.net

category: Networking
license: LGPL

dependencies:
  base:       ">=4.15  && <4.18"
  clock:      ">=0.8.2 && <0.9"
  cryptonite: ">=0.29  && <0.31"
  ip:         ">=1.7   && <1.8"
  memory:     ">=0.16  && <0.19"
  network:    ">=3.1   && <3.2"
  text:       ">=1.2   && <2.1"
  time:       ">=1.9   && <1.10"
  vector:     ">=0.12  && <0.13"
  vector-sized: ">=1.4 && <1.5"
  wide-word:  ">=0.1 && < 0.2"

default-extensions:
  - BangPatterns
  - ForeignFunctionInterface
  - CPP
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - DerivingVia
  - DeriveAnyClass
  - ScopedTypeVariables
  - KindSignatures
  - DataKinds
  - TypeApplications
  - DeriveGeneric
  - OverloadedStrings
  - StandaloneDeriving
  - ViewPatterns

library:
  c-sources:
    - wireguard/wireguard.c
    - System/Network/linkstatus.c
  include-dirs: wireguard/
  exposed-modules:
    - System.Network.Wireguard

flags:
  aeson:
    description: Enable ToJSON/FromJSON instances with Aeson
    manual: true
    default: false

  beam:
    description: Enable Beamxo serializers/deserializers
    manual: true
    default: false

  hashable:
    description: Enable Hashable instances
    manual: true
    default: false

when:
  - condition: flag(aeson)
    dependencies:
      aeson: ">=2.0 && <2.1"
      base64: ">=0.4 && <0.5"
    cpp-options: -DWITH_AESON=1

  - condition: flag(hashable)
    dependencies:
      hashable: ">=1.4 && <1.5"
    cpp-options: -DWITH_HASHABLE=1

  - condition: flag(beam)
    dependencies:
      beam-core: ">=0.9 && <0.11"
      bytestring: ">=0.10 && <0.11"
    cpp-options: -DWITH_BEAM=1
    default-extensions:
      - FlexibleInstances
      - FlexibleContexts
      - MultiParamTypeClasses
      - UndecidableInstances
